# Generated by Django 2.2.5 on 2020-08-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto_confian',
            name='idUsuario',
        ),
    ]
