# Generated by Django 2.2.5 on 2020-07-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_confian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_1', models.CharField(blank=True, max_length=50)),
                ('contacto_2', models.CharField(blank=True, max_length=50)),
                ('idPersona', models.ManyToManyField(db_table='detalle_persona_confi', to='Api.Persona')),
            ],
            options={
                'verbose_name': 'Contacto_Confi',
                'db_table': 'mant_persona_confian',
            },
        ),
    ]
