# Generated by Django 2.2.5 on 2020-08-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_contacto_confian_idusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'db_table': 'conf_rol',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='idRol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.Roles'),
            preserve_default=False,
        ),
    ]
