# Generated by Django 2.2.5 on 2020-08-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20200817_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idRol',
        ),
    ]
