# Generated by Django 2.2.5 on 2020-08-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_remove_usuario_idrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idRol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.Roles'),
        ),
    ]
